  let a= ("---------------- $$$$ Report card $$$$----------------------")
console.log( a)
let name=("Name- Pihu")
console.log( name)
let b=("School- M.P.E.C")
  let c= (" grade - A+")        
 console.log( c)
let s=(" Section - A")
 console.log( s)
let z = (" Roll no.-20")
console.log ( z)
let e=("English - 30")
       console.log(e)
let r=(" Maths - 25")
console.log( r)
let d=(" Science - 45")
console.log( d)
